Repository Evarisk/DoliSIRH, pull requests merged in 2023-05, with the labels that each got.

#265 #198 [Dashboard] add: manage years
  dolisirhindex.php
Labels: 1, Enhancement

#263 #205 [Trad] fix: change trad
  langs/fr_FR/dolisirh.lang
Labels: 0, Bug

#266 #242 [Timesheet] add: create timesheet with prefill date at M-1
  langs/fr_FR/dolisirh.lang
  view/timesheet/timesheet_card.php
Labels: 2, Enhancement

#267 #262 [Timesheet] add: notice error config project/task conf
  langs/fr_FR/dolisirh.lang
  view/timesheet/timesheet_card.php
Labels: 2, Enhancement

#274 #273 [TimeSpent] fix: week view didn't send hourdate info in action
  view/timespent_week.php
Labels: 1, Bug

#276 #275 [Trad] fix: spelling error
  langs/fr_FR/dolisirh.lang
Labels: 0, Translation
