Repository Evarisk/DoliSIRH, pull requests merged in 2023-07, with the labels that each got.

#332 #331 [Lib] fix: modal open with 1 input hidden
  lib/dolisirh_function.lib.php
Labels: 1, Bug

#270 #230 [Certificate] add: certificate object
  admin/certificate.php
  admin/dolisirhdocuments.php
  class/certificate.class.php
  class/dolisirhdocuments.class.php
  core/modules/dolisirh/certificate/mod_certificate_standard.php
  core/modules/dolisirh/dolisirhdocuments/certificatedocument/doc_certificatedocument_odt.modules.php
  core/modules/dolisirh/dolisirhdocuments/certificatedocument/mod_certificatedocument_standard.php
  core/modules/dolisirh/dolisirhdocuments/certificatedocument/modules_certificatedocument.php
  core/triggers/interface_99_modDolisirh_DolisirhTriggers.class.php
  documents/doctemplates/certificatdocument/index.php
  documents/doctemplates/certificatedocument/index.php
  documents/doctemplates/certificatedocument/template_certificatedocument.odt
  langs/fr_FR/dolisirh.lang
  lib/dolisirh.lib.php
  lib/dolisirh_certificate.lib.php
  sql/certificate/llx_saturne_certificate.key.sql
  sql/certificate/llx_saturne_certificate.sql
  sql/certificate/llx_saturne_certificate_extrafields.key.sql
  sql/certificate/llx_saturne_certificate_extrafields.sql
  view/certificate/certificate_agenda.php
  view/certificate/certificate_attendants.php
  view/certificate/certificate_card.php
  view/certificate/certificate_list.php
  view/certificate/certificate_note.php
Labels: 3, Enhancement

#271 #232 [Admin] add: remove about page for use saturne instead
  admin/about.php
  lib/dolisirh.lib.php
Labels: 1, Enhancement

#287 #283 #284 [Lib] fix: num_between_day return 1 if daysNumber is empty
  lib/dolisirh_function.lib.php
Labels: 1, Bug

#304 #241 [Documents] add: remove DoliSIRHDocuments and use saturneDocuments class
  class/dolisirhdocuments.class.php
  class/dolisirhdocuments/certificatedocument.class.php
  class/dolisirhdocuments/timesheetdocument.class.php
Labels: 2, Enhancement

#303 [Certificate] add: improve certificate
  view/certificate/certificate_card.php
Labels: 3, Enhancement

#299 [Mod] add: remove element/files
  admin/dolisirhdocuments.php
  class/dashboarddolisirhstats.class.php
  core/tpl/dolisirh_dashboard.tpl.php
  core/tpl/index.php
  css/scss/element/_dashboard-box.scss
  css/scss/element/_element.scss
  js/dolisirh.min.js
  lib/dolisirh_function.lib.php
Labels: 2, Enhancement

#305 #281 [Dashboard] fix: dispaly year with SOCIETE_FISCAL_MONTH_START interval
  class/dolisirhstats.class.php
Labels: 2, Bug

#313 #312 [Dashboard] fix: missing saturne
  dolisirhindex.php
Labels: 1, Bug

#345 #344 [CI/CD] add: editor config file for match PSR-12 conventions
  .editorconfig
Labels: 2, Enhancement

#300 #236 [Dashboard] add: DolisirhDashboard class for manage dashboard
  class/actions_dolisirh.class.php
  class/dolisirhdashboard.class.php
  core/modules/modDoliSIRH.class.php
  dolisirhindex.php
Labels: 3, Enhancement

#343 #342 [Mod] add: missing global moduleNameUpperCase
  dolisirh.main.inc.php
Labels: 0, Enhancement

#339 #337 [Triggers] clean code triggers
  core/triggers/interface_99_modDolisirh_DolisirhTriggers.class.php
Labels: 1, Enhancement

#341 #340 [Mod] fix: remove changelod for prevent conflict
  ChangeLog.md
Labels: 0, Bug

#353 #347 [SQL] clean: use space indent and update SQL
  sql/data.sql
  sql/dolisirhdocuments/llx_dolisirh_dolisirhdocuments.key.sql
  sql/dolisirhdocuments/llx_dolisirh_dolisirhdocuments.sql
  sql/dolisirhdocuments/llx_dolisirh_dolisirhdocuments_extrafields.key.sql
  sql/dolisirhdocuments/llx_dolisirh_dolisirhdocuments_extrafields.sql
  sql/llx_c_timesheet_attendants_role.sql
  sql/llx_categorie_invoice.key.sql
  sql/llx_categorie_invoice.sql
  sql/llx_categorie_invoicerec.key.sql
  sql/llx_categorie_invoicerec.sql
  sql/llx_element_workinghours.sql
  sql/timesheet/llx_categorie_timesheet.key.sql
  sql/timesheet/llx_categorie_timesheet.sql
  sql/timesheet/llx_dolisirh_timesheet.key.sql
  sql/timesheet/llx_dolisirh_timesheet.sql
  sql/timesheet/llx_dolisirh_timesheet_extrafields.key.sql
  sql/timesheet/llx_dolisirh_timesheet_extrafields.sql
  sql/timesheet/llx_dolisirh_timesheetdet.key.sql
  sql/timesheet/llx_dolisirh_timesheetdet.sql
  sql/timesheet/llx_dolisirh_timesheetdet_extrafields.key.sql
  sql/timesheet/llx_dolisirh_timesheetdet_extrafields.sql
  sql/update.sql
Labels: 1, Enhancement

#352 #346 [IMG] clean: change name img
  admin/project.php
  admin/setup.php
  admin/timesheet.php
  class/actions_dolisirh.class.php
  core/modules/modDoliSIRH.class.php
  documents/temp/index.php
  dolisirhindex.php
  img/dolisirh_color.png
  img/object_certificate.png
  img/object_certificate_small.png
  img/object_dolisirh_color.png
  img/object_timesheet.png
  img/object_timesheet_small.png
Labels: 1, Enhancement

#301 #237 [TimeSheet] add: rework class for use SaturneObject
  class/timesheet.class.php
  core/triggers/interface_99_modDolisirh_DolisirhTriggers.class.php
  view/timesheet/timesheet_card.php
Labels: 2, Enhancement

#356 #351 [Trad] clean: remove trad / align
  langs/en_US/dolisirh.lang
  langs/en_US/index.php
  langs/fr_FR/dolisirh.lang
  langs/fr_FR/tools.lang
Labels: 1, Enhancement

#357 #350 [Lib] clean: lib files
  lib/dolisirh.lib.php
  lib/dolisirh_certificate.lib.php
  lib/dolisirh_timesheet.lib.php
Labels: 1

#355 #349 [Mod] clean: mod file
  core/modules/dolisirh/certificate/mod_certificate_standard.php
  core/modules/dolisirh/dolisirhdocuments/certificatedocument/mod_certificatedocument_standard.php
  core/modules/dolisirh/dolisirhdocuments/certificatedocument/modules_certificatedocument.php
  core/modules/dolisirh/dolisirhdocuments/projectdocument/mod_projectdocument_standard.php
  core/modules/dolisirh/dolisirhdocuments/projectdocument/modules_projectdocument.php
  core/modules/dolisirh/dolisirhdocuments/timesheetdocument/mod_timesheetdocument_standard.php
  core/modules/dolisirh/dolisirhdocuments/timesheetdocument/modules_timesheetdocument.php
  core/modules/dolisirh/modules_dolisirh.php
  core/modules/dolisirh/timesheet/mod_timesheet_standard.php
  core/modules/modDoliSIRH.class.php
Labels: 1, Enhancement

#354 #349 [Admin] clean: optimize hrProjectTask and clean code
  admin/project.php
  admin/setup.php
  admin/timesheet.php
  langs/fr_FR/dolisirh.lang
  lib/dolisirh.lib.php
Labels: 1, Enhancement

#365 #359 [Admin] fix: warning and missing info
  class/actions_dolisirh.class.php
  class/certificate.class.php
  core/modules/dolisirh/dolisirhdocuments/timesheetdocument/mod_timesheetdocument_standard.php
Labels: 1, Bug

#366 #360 [ODT] clean: odt files with saturne
  core/modules/dolisirh/dolisirhdocuments/certificatedocument/doc_certificatedocument_odt.modules.php
  core/modules/dolisirh/dolisirhdocuments/projectdocument/doc_projectdocument_odt.modules.php
  core/modules/dolisirh/dolisirhdocuments/timesheetdocument/doc_timesheetdocument_odt.modules.php
Labels: 2, Enhancement, ODT

#367 #361 [SQL] add: remove documents for use saturne instead
  sql/dolisirhdocuments/index.php
  sql/dolisirhdocuments/llx_dolisirh_dolisirhdocuments.key.sql
  sql/dolisirhdocuments/llx_dolisirh_dolisirhdocuments.sql
  sql/dolisirhdocuments/llx_dolisirh_dolisirhdocuments_extrafields.key.sql
  sql/dolisirhdocuments/llx_dolisirh_dolisirhdocuments_extrafields.sql
Labels: 0, Enhancement

#368 #362 [Index] clean: small clean weak warning
  dolisirhindex.php
Labels: 0, Enhancement

#369 #363 [JS/CSS] clean: rebuild JS/CSS and clean js files
  css/dolisirh.min.css
  css/scss/element/_modal-timespent.scss
  css/scss/element/_task-progress.scss
  js/dolisirh.min.js
  js/modules/dashboard.js
  js/modules/task.js
Labels: 1, Enhancement

#387 #326 #377 [Trad] clean: all trads are better organised
  langs/fr_FR/dolisirh.lang
  view/workinghours_card.php
Labels: 2, Enhancement, Translation

#379 #364 [Hook] add: tags functionnality
  class/actions_dolisirh.class.php
Labels: 2, Enhancement

#385 #73 [TimeSpent] add: rework timespent view with range instead of 3 views
  admin/setup.php
  core/modules/modDoliSIRH.class.php
  js/dolisirh.min.js
  js/modules/task.js
  lib/dolisirh_timespent.lib.php
  view/timesheet/timesheet_card.php
  view/timespent_day.php
  view/timespent_month.php
  view/timespent_range.php
  view/timespent_week.php
Labels: 3, Enhancement

#394 #391 [Lib] fix: change function name dolisirh_num_between_days
  class/dolisirhdashboard.class.php
  class/dolisirhstats.class.php
  core/modules/dolisirh/dolisirhdocuments/timesheetdocument/doc_timesheetdocument_odt.modules.php
  lib/dolisirh_function.lib.php
  lib/dolisirh_timespent.lib.php
  view/timesheet/timesheet_card.php
  view/timespent_range.php
Labels: 1, Enhancement

#386 #330 [TimeSheet] add: new service on timesheet line
  admin/setup.php
  class/timesheet.class.php
  core/triggers/interface_99_modDolisirh_DolisirhTriggers.class.php
  langs/fr_FR/dolisirh.lang
  lib/dolisirh.lib.php
  view/timesheet/timesheet_card.php
Labels: 2, Enhancement

#393 #372 [ODT] add: new certificate
  documents/doctemplates/certificatedocument/template_certificatedocument.odt
Labels: 1, Enhancement, ODT

#421 #418 [ODT] add: implementation and improve certificate document
  core/modules/dolisirh/dolisirhdocuments/certificatedocument/doc_certificatedocument_odt.modules.php
  documents/doctemplates/certificatedocument/template_certificatedocument.odt
Labels: 2, Enhancement, ODT

#410 Add improve get timesheet product service function
  admin/project.php
  admin/setup.php
  core/modules/modDoliSIRH.class.php
  core/triggers/interface_99_modDolisirh_DolisirhTriggers.class.php
  lib/dolisirh.lib.php
  lib/dolisirh_function.lib.php
Labels: 2, Enhancement

#399 #384 [Timespent] add: rework in one list timespent_range
  view/timespent_range.php
Labels: 3, Enhancement

#408 #403 [SQL] add: entity for timesheetdet
  class/timesheet.class.php
  sql/timesheet/llx_dolisirh_timesheetdet.sql
  sql/update.sql
Labels: 0, Data model, Enhancement

#400 #392 [Certificate] add: crontab checkDateEnd
  core/modules/modDoliSIRH.class.php
  view/certificate/certificate_card.php
Labels: 3, Enhancement

#409 #402 [TimeSheet] fix: remove fetch timesheetdet
  class/timesheet.class.php
Labels: 0, Enhancement

#397 #378 [Class] fix: missing include and rename functions
  class/dolisirhdashboard.class.php
  class/dolisirhdocuments/certificatedocument.class.php
  class/dolisirhdocuments/timesheetdocument.class.php
  class/dolisirhstats.class.php
  core/modules/dolisirh/dolisirhdocuments/timesheetdocument/doc_timesheetdocument_odt.modules.php
Labels: 3, Enhancement

#396 #376 [Triggers] add: certificate triggers
  core/triggers/interface_99_modDolisirh_DolisirhTriggers.class.php
Labels: 2, Enhancement

#426 #424 [Admin] fix: HR_PROJECT creation don't create all tasks and missing contact assign
  admin/setup.php
Labels: 2, Bug

#398 #183 [Timespent] add: change view density and more task info
  lib/dolisirh_timespent.lib.php
Labels: 1, Enhancement

#422 #420 [SQL] add: certificate attendants role
  core/modules/modDoliSIRH.class.php
  sql/data.sql
  sql/llx_c_certificate_attendants_role.sql
Labels: 2, Data model, Enhancement

#419 #411 [Admin] add: conf certificateUserResponsible
  admin/setup.php
  core/modules/modDoliSIRH.class.php
  core/triggers/interface_99_modDolisirh_DolisirhTriggers.class.php
  langs/fr_FR/dolisirh.lang
Labels: 2, Enhancement

#423 #417 [TimeSheet] clean timesheet view
  class/timesheet.class.php
  core/modules/modDoliSIRH.class.php
  langs/fr_FR/dolisirh.lang
  lib/dolisirh_timespent.lib.php
  view/timesheet/timesheet_card.php
  view/timesheet/timesheet_list.php
Labels: 2, Enhancement

#288 #89 [Lang] add: bold to delete timesheet formconfirm
  langs/fr_FR/dolisirh.lang
Labels: 0, Enhancement

#383 #337 [Certificat] clean: view and lib
  class/actions_dolisirh.class.php
  core/modules/dolisirh/dolisirhdocuments/projectdocument/doc_projectdocument_odt.modules.php
  core/modules/modDoliSIRH.class.php
  lib/dolisirh_certificate.lib.php
  sql/certificate/llx_categorie_certificate.key.sql
  sql/certificate/llx_categorie_certificate.sql
  view/certificate/certificate_card.php
Labels: 2, Enhancement

#432 #420 [SQL] fix: dictionary certificate attendants
  core/modules/modDoliSIRH.class.php
  sql/data.sql
Labels: 0, Bug

#435 #431 [Dashboard] fix: label data with timeSpentOnTasks
  class/dolisirhdashboard.class.php
Labels: 1, Bug

#434 #433 [Hook] fix: wrong ID constructCategory hookl on certificate
  class/actions_dolisirh.class.php
  core/modules/modDoliSIRH.class.php
  langs/fr_FR/dolisirh.lang
Labels: 1, Bug

#436 #430 [Triigers] fix: timeSheetLine error fetch product ID
  core/triggers/interface_99_modDolisirh_DolisirhTriggers.class.php
Labels: 1, Bug

#437 #429 [Certificate] clean: view
  view/certificate/certificate_card.php
Labels: 3, Enhancement

#438 #293 [JS] add: reload element_type and fk_element field
  js/dolisirh.min.js
  js/modules/certificate.js
  js/modules/task.js
  view/certificate/certificate_card.php
Labels: 2, Enhancement

#440 #439 [ODT] fix: missing responsible signature
  core/modules/dolisirh/dolisirhdocuments/certificatedocument/doc_certificatedocument_odt.modules.php
  documents/doctemplates/certificatedocument/template_certificatedocument.odt
  view/certificate/certificate_card.php
Labels: 1, Bug, ODT

#444 #443 [Admin] fix: error creation product with barcode module
  admin/setup.php
  core/modules/modDoliSIRH.class.php
Labels: 1, Bug

#446 #445 [Mod] fix: inconsistency backward product
  core/modules/modDoliSIRH.class.php
Labels: 1, Bug

#474 #467 [TimeSheetDocument] fix: tzuser signature date and signature file error
  core/modules/dolisirh/dolisirhdocuments/timesheetdocument/doc_timesheetdocument_odt.modules.php
Labels: 1, Bug

#478 #476 [PDF] fix: no more auto download after pdf generation
  view/certificate/certificate_card.php
  view/timesheet/timesheet_card.php
Labels: 1, Bug

#477 #475 [TimeSpent] fix: use SaturneTask to avoid useless hook
  class/actions_dolisirh.class.php
  lib/dolisirh_timespent.lib.php
  view/timespent_range.php
Labels: 2, Enhancement

#472 #471 [Mod] fix: trad rights
  core/modules/modDoliSIRH.class.php
  langs/fr_FR/dolisirh.lang
Labels: 1, Bug

#473 #470 [Mod] fix: clean various files
  class/timesheet.class.php
  core/modules/dolisirh/dolisirhdocuments/certificatedocument/modules_certificatedocument.php
  core/triggers/interface_99_modDolisirh_DolisirhTriggers.class.php
  langs/fr_FR/dolisirh.lang
  sql/certificate/index.php
  view/timesheet/timesheet_card.php
Labels: 1, Enhancement
