Repository Evarisk/DoliSIRH, pull requests merged in 2023-09, with the labels that each got.

#505 #504 [View] fix: fatal banner actions
  view/certificate/certificate_card.php
  view/timesheet/timesheet_card.php
Labels: 1, Bug

#513 #512 [JS] add: fix table header timespent on scroll events
  lib/dolisirh_timespent.lib.php
  view/timespent_range.php
Labels: 3, Enhancement

#517 #516 [Timesheet] fix: missing rights
  core/modules/modDoliSIRH.class.php
  view/timesheet/timesheet_card.php
Labels: 1, Enhancement

#518 #509 [Timespent] add: checkbox for select logic operators
  js/dolisirh.min.js
  js/modules/task.js
  langs/fr_FR/dolisirh.lang
  lib/dolisirh_timespent.lib.php
  view/timespent_range.php
Labels: 2, Enhancement

#519 #506 [IHM] add: picto unlock
  view/certificate/certificate_card.php
  view/timesheet/timesheet_card.php
Labels: 1, Enhancement, IHM

#427 #425 [Mod] add: new version number 1.4.0
  README.md
  core/modules/modDoliSIRH.class.php
  core/triggers/interface_99_modDolisirh_DolisirhTriggers.class.php
  js/dolisirh.min.js
Labels: 1, Enhancement
