Repository Evarisk/DoliSIRH, pull requests merged in 2023-12, with the labels that each got.

#535 #534 [TimeSpent] fix: compatibility 18 with element_time
  class/actions_dolisirh.class.php
  class/timesheet.class.php
  core/modules/modDoliSIRH.class.php
  lib/dolisirh_timespent.lib.php
  view/timesheet/timesheet_card.php
  view/timespent_list.php
Labels: 3, Bug

#539 #538 [Hook] fix: hook name
  class/actions_dolisirh.class.php
Labels: 0, Bug

#543 #542 [Mod] add: modAgenda dependancies
  core/modules/modDoliSIRH.class.php
Labels: 0, Bug

#553 #552 [List] add: change sortfield and sortorder in date_creation DESC
  view/certificate/certificate_list.php
  view/timesheet/timesheet_list.php
Labels: 0, Enhancement

#541 #540 [Hook] fix: remove hook now in saturne
  class/actions_dolisirh.class.php
Labels: 0, Enhancement

#554 #551 [Mod] add: new version number 1.5.0
  README.md
  core/modules/modDoliSIRH.class.php
  core/triggers/interface_99_modDolisirh_DolisirhTriggers.class.php
Labels: 0, Enhancement
