Repository Evarisk/DoliSIRH, pull requests merged in 2023-08, with the labels that each got.

#482 #481 [Trad] fix: wrong trad
  langs/fr_FR/dolisirh.lang
  view/workinghours_card.php
Labels: 0, Translation

#485 #484 [Task] fix: fatal on time spent list
  class/actions_dolisirh.class.php
Labels: 1, Bug

#486 #483 [WorkingHours] add: admin can now edit all users' working hours
  view/workinghours_card.php
Labels: 1, Enhancement

#490 #489 [List] add: status filter
  view/certificate/certificate_list.php
  view/timesheet/timesheet_list.php
Labels: 1, Enhancement

#480 #479 [Hook] add: task create action
  class/actions_dolisirh.class.php
  langs/fr_FR/dolisirh.lang
Labels: 2, Enhancement

#488 #487 [TimeSheet] fix: product backward compatibility
  admin/setup.php
Labels: 1, Bug

#496 #495 [Class] fix: remove typage on $ismultientitymanaged
  class/certificate.class.php
  class/dolisirhdocuments/certificatedocument.class.php
  class/dolisirhdocuments/projectdocument.class.php
  class/dolisirhdocuments/timesheetdocument.class.php
  class/timesheet.class.php
  core/modules/dolisirh/dolisirhdocuments/certificatedocument/doc_certificatedocument_odt.modules.php
  core/modules/dolisirh/dolisirhdocuments/projectdocument/doc_projectdocument_odt.modules.php
  core/modules/dolisirh/dolisirhdocuments/timesheetdocument/doc_timesheetdocument_odt.modules.php
Labels: 1, Bug

#500 #498 [Class] fix: dolibarr 18 typage
  class/timesheet.class.php
Labels: 0, Bug
