Repository Evarisk/DoliSIRH, pull requests merged in 2024-09, with the labels that each got.

#599 #598 fix: fatal on certificat doc creation
  core/modules/dolisirh/dolisirhdocuments/certificatedocument/doc_certificatedocument_odt.modules.php
Labels: 0

#565 #564 [Hook] fix: elementtype without the ptt for projectdocument task
  class/actions_dolisirh.class.php
  core/modules/dolisirh/dolisirhdocuments/projectdocument/doc_projectdocument_odt.modules.php
Labels: 1, Bug

#601 #600 [Cards] fix: use saturne for lock and archive
  view/certificate/certificate_card.php
  view/timesheet/timesheet_card.php
Labels: 1, Enhancement

#606 #605 [Mod] add: new version number 1.5.1
  README.md
  core/modules/modDoliSIRH.class.php
  core/triggers/interface_99_modDolisirh_DolisirhTriggers.class.php
Labels: 0, Enhancement

#610 #609 [RecurringInvoiceStats] fix: fatal
  view/recurringinvoicestatistics.php
Labels: 1, Bug

#612 #611 [Hook] fix: missing parseInt and check int + cast
  class/actions_dolisirh.class.php
  lib/dolisirh_timespent.lib.php
Labels: 1, Bug

#614 #613 [TimeSheet] fix: missing qty check and fk_user_assign
  class/timesheet.class.php
  langs/fr_FR/dolisirh.lang
  view/timesheet/timesheet_card.php
Labels: 1, Bug
